export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    SELECT_CATEGORY: "SELECT_CATEGORY",
    SELECT_OF_CATEGORY: "SELECT_OF_CATEGORY",
    SELECT_DISCOUNT: "SELECT_DISCOUNT",
    SELECT_LIMITED: "SELECT_LIMITED",
    SELECT_SELLING: "SELECT_SELLING",

    SELECT_LIST_PRODUCT: "SELECT_LIST_PRODUCT",

    SELECT_PRODUCT_ROOM: "SELECT_PRODUCT_ROOM",
    SELECT_ROOM_TYPES: "SELECT_ROOM_TYPES",
    SELECT_PRODUCT_BY_MATERIAL: "SELECT_PRODUCT_BY_MATERIAL",
    SELECT_PRODUCT_BY_THUONGHIEU: "SELECT_PRODUCT_BY_THUONGHIEU",
    SELECT_BEST_SELLING: "SELECT_BEST_SELLING",

    SELECT_RELATED_PRODUCT: "SELECT_RELATED_PRODUCT",
    SELECT_COMMENT: "SELECT_COMMENT",
    SELECT_USER: "SELECT_USER",
}