USE [master]
GO

/****** Object:  Database [DoAnCoSo2]    Script Date: 11/19/2021 4:27:03 PM ******/
CREATE DATABASE [DoAnCoSo2] ON  PRIMARY 
( NAME = N'DoAnCoSo2', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLBOS\MSSQL\DATA\DoAnCoSo2.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DoAnCoSo2_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLBOS\MSSQL\DATA\DoAnCoSo2_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DoAnCoSo2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DoAnCoSo2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET ARITHABORT OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DoAnCoSo2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DoAnCoSo2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DoAnCoSo2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DoAnCoSo2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DoAnCoSo2] SET  MULTI_USER 
GO

ALTER DATABASE [DoAnCoSo2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DoAnCoSo2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DoAnCoSo2] SET  READ_WRITE 
GO

